[package]
name = "soft-computing-assignment-4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
neuroflow = "0.2.0"
rand = "0.8.5"
scan_fmt = "0.2.6"
